{
 "title": "Proyecto Habeetat Copy",
 "description": "Dashboard del proyecto Habeetat",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  Temperatura\nFROM Datos_Sensores\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  Temperatura\nFROM Datos_Sensores\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Humedad",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  Humedad\nFROM Datos_Sensores\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Concentración de CO2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  VoltajeAnalogico\nFROM Datos_Sensores\nWHERE\n  $__timeFilter(fecha)\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Humedad",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  Humedad\nFROM Datos_Sensores\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Concentración de CO2",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  VoltajeAnalogico\nFROM Datos_Sensores\nORDER BY fecha"
    }
   ]
  }
 ]
}